### ISSUE TITLE
Searching on CONCAT field from join

### ISSUE THREAD

**Issue by jammy-git** [laravel-enso/VueDatatable#105]
This is  a question.

First of all, great datatable plugin. We're using it as a standalone plugin as we'd already built the app and didn't want to integrate the whole Enso ecosystem, but even still it's definitely the best datatable component we've tried so far.

On to the issue we're having. We have a Model that has a polymorphic relationship to an Address model. We're pulling in the address data in a single field using a CONCAT statement in a join to the query in the table builder file. However it seems that doing it this way is causing problems with searching as the query that is created when searching uses the field alias which obviously doesn't exist in the db.

Is is possible to, instead of using a CONCAT statement when querying the database, send all the data as separate fields to the datatable and then concatenate it via the json config file. Maybe something in the data attribute like `"data": "address.address_1 + address.address_2 + address.region"`?

**Comment by gandesc** [comment]
Hi Jammy, 

Thanks for the praise, glad you like it.

In order to have the data available and searchable at the same time,
one way of doing it would be to still do the concatenation (but have it non searchable),
include in the select the address columns you want searchable,
add them in the template, but mark them as rogue.

From the [docs](https://docs.laravel-enso.com/packages/vue-datatable.html#template):
![image](https://user-images.githubusercontent.com/14071925/48910859-bdf1e400-ee79-11e8-9109-75fe352fd2db.png)

Be sure to go through the docs as you may find other useful features.

**Comment by jammy-git** [comment]
That works! Awesome, thanks.
