### ISSUE TITLE
Cannot compile with laravel and npm run watch

### ISSUE THREAD

**Issue by Xpedigo** [laravel-enso/VueDatatable#120]
This is  a **bug**.

### Prerequisites
* [X ] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
* [ x] Did you check the documentation?
* [ x] Did you perform a cursory search?

### Description

Hi trying to install the plugin with laravel-enso/vuedatable, and I just get this message 

``ERROR in ./resources/js/components/enso/bulma/toastr/Notification.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/components/enso/bulma/toastr/Notification.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '../../../../store'``

Every dependencies are installed though...

Any idea?

Thank you.

**Comment by aocneanu** [comment]
I guess you're using the table outside Enso?

**Comment by Xpedigo** [comment]
Hi!

Yes, just removed the store reference and it works, is that all?

Thx

**Comment by aocneanu** [comment]
Hi,

Actually no, the table will try to use a toastr on certain actions, and for that to work I will have to change something in the way notifications are handled because right now is too deeply integrated with Enso. It needs the `store` because the toastr's position can be customized per user.

But in the near future I'll take care of it. If you don't need `toastr` functionality than you're good to go, but that also means that you will use the package at 25% of its potential :)

**Comment by Xpedigo** [comment]
@aocneanu When you have time just take a look at the email i've sent to you, it's about this subject :).

Thank you!

**Comment by carlosaruales** [comment]
I have the same problem. I have all the Prerequisites but it's not work.  I use it outside enso too.
