### ISSUE TITLE
Is Laravel required?

### ISSUE THREAD

**Issue by IvoPereira** [laravel-enso/VueDatatable#75]
This is  a **feature request**.

### Description

I was looking for a good DataTable solution and I've come across this repo. However, from what I can understand from the install instructions, I am required to use it with Laravel?

Isn't there any standalone version of the VueDatatable itself or am I missing something?

**Comment by gandesc** [comment]
Hi,

We're flattered that you consider the package to be a good DataTable solution.

In short, yes, the package as a whole requires you to use Laravel, since the backend is designed to be used with it. Moreover, the data table package is included in our customized Enso ecosystem.

Having said that, the front end components depend on VueJS and a few other libraries and, after retrieving a table configuration, pull the data that needs to be displayed. That means that, in principle, you could pair it with a different back-end, if the contracts are respected.

**Comment by aocneanu** [comment]
Can we close this?
